# Define all 3 services, and how they run
services:
  db:
    image: mysql:8.0
    container_name: db
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    # Uncomment 2 lines below to expose port 3333 to host (debugging)
    #ports:
      #- "3333:3306"
    networks:
      - app_net
  
  # The entry-point is defined here, not in the backend Dockerfile
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # Uncomment below 2 lines to re-map port to host #
    #ports:
      #- "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/${DB_NAME}
    depends_on:
      - db
    networks:
      - app_net
    
    # Exposes frontend port 80 to host machine port 8080
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_net

# Create a volume for persistent SESSION data storage.
# Data will be stored for the duration of the DB container LIFE.
# You can start/stop the container, the volume data will persist.
# The SESSION data in the volume does not persist through multiple compositions.

# The data scripts in "sql-scripts" will be re-ran everytime you re-compose.

volumes:
  mysql_data:

# Network for containers to communicate on
networks:
  app_net:
    driver: bridge