version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: cd-416-db
    environment: 
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    # Uncomment 2 lines below to expose 3333 to host
    #ports:
    #  - "3333:3306"
    networks:
      - app_net
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    # Uncomment below 2 lines to re-map port to host #
    #ports:
      #- "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${DB_USER}:${DB_PASSWORD}@db:3306/{DB_NAME}
    depends_on:
      - db
    networks:
      - app_net
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_app
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
    - app_net

volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge